### ISSUE TITLE
Regarding Coder Foundry

### ISSUE THREAD

**Issue by shinmendokkodo** [calebj516/TheBugTracker#1]
Hi, I was looking to enroll my-self in some bootcamp.
I came across Coder Foundry.
The curriculum and projects look decent.

Looking for coder foundry projects on github, I came across your repo.
Just wanted to know from you how was your experience with coder foundry.

Thanks.

**Comment by calebj516** [comment]
Hey there, happy to help.

Overall my experience has been very good. In particular, the support on Discord is awesome. However, there is one thing I wish I was told about before I signed up. A couple of the projects (the bug tracker, and another application they call Movie Pro) are not complete; the curriculum gets you about 75% of the way there and then you are on your own.

One can argue that this helps the learning process because you have to figure things out by yourself, and if you are a very motivated individual you will be probably be just fine, but I went in with the impression that the courses were 100% complete. Not really a huge problem but it kind of irritated me a little.

Hope this helps.
